name: demo_showcase
description: Demo showcase flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  surf_mwwm: ^0.0.1-dev.2

  surf_injector: ^0.0.1-dev.2

  surf_network: ^0.0.1-dev.4

  surf_logger: ^0.0.1-dev.4

  surf_util: ^0.0.1-dev.9

  get_storage: 1.3.2

  flutter_masked_text: 0.8.0

flutter:

  uses-material-design: true